# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstHandbellPeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=b'date')),
                ('building', models.CharField(max_length=31, verbose_name=b'town')),
                ('town', models.CharField(max_length=31, verbose_name=b'town')),
                ('county', models.CharField(max_length=31, verbose_name=b'county')),
                ('region', models.CharField(max_length=31, verbose_name=b'region')),
                ('country', models.CharField(max_length=31, verbose_name=b'country')),
                ('address', models.CharField(max_length=31, verbose_name=b'address')),
                ('location', models.CharField(max_length=31, verbose_name=b'address')),
                ('has_location', models.BooleanField(default=False, verbose_name=b'has_location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FirstTowerbellPeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name=b'date')),
                ('building', models.CharField(max_length=31, verbose_name=b'town')),
                ('town', models.CharField(max_length=31, verbose_name=b'town')),
                ('county', models.CharField(max_length=31, verbose_name=b'county')),
                ('region', models.CharField(max_length=31, verbose_name=b'region')),
                ('country', models.CharField(max_length=31, verbose_name=b'country')),
                ('address', models.CharField(max_length=31, verbose_name=b'address')),
                ('location', models.CharField(max_length=31, verbose_name=b'address')),
                ('has_location', models.BooleanField(default=False, verbose_name=b'has_location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'id')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name=b'title')),
                ('slug', models.SlugField(max_length=255, verbose_name=b'slug')),
                ('name', models.CharField(max_length=255, verbose_name=b'name')),
                ('raw_notation', models.CharField(max_length=1023, verbose_name=b'notation')),
                ('notation', models.CharField(max_length=1023, verbose_name=b'notation')),
                ('leadHead', models.CharField(blank=True, default=b'', max_length=63, verbose_name=b'lead head')),
                ('leadHeadCode', models.CharField(max_length=31, verbose_name=b'lead head code')),
                ('classification', models.CharField(max_length=255, verbose_name=b'classification')),
                ('method_notes', models.CharField(max_length=255, verbose_name=b'method notes')),
                ('falseness_groups', models.CharField(max_length=31, verbose_name=b'fchGroups')),
                ('rw_reference', models.CharField(max_length=63, verbose_name=b'"Ringing World" reference')),
                ('bn_reference', models.CharField(max_length=63, verbose_name=b'"The Bell News" reference')),
                ('cb_reference', models.CharField(max_length=63, verbose_name=b'"Church Bells" reference')),
                ('pmm_reference', models.CharField(max_length=63, verbose_name=b'Numerical index in the Plain Minor Methods collection')),
                ('tdmm_reference', models.CharField(max_length=63, verbose_name=b'Numerical index in the Treble Dodging Minor Methods collection')),
                ('first_hb_peal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstHandBellPeak', to='methods.FirstHandbellPeal')),
                ('first_tb_peal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstTowerBellPeak', to='methods.FirstTowerbellPeal')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MethodSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=255, verbose_name=b'notes')),
                ('slug', models.SlugField(max_length=255, verbose_name=b'slug')),
                ('p_stage', models.IntegerField(verbose_name=b'properties->stage')),
                ('p_lengthOfLead', models.IntegerField(verbose_name=b'properties->lengthOfLead')),
                ('p_numberOfHunts', models.IntegerField(verbose_name=b'properties->numberOfHunts')),
                ('p_huntBellPath', models.CharField(max_length=511, verbose_name=b'properties->huntBellPath')),
                ('p_symmetry', models.CharField(max_length=31, verbose_name=b'properties->symmetry')),
                ('uniq_hash', models.CharField(max_length=57, unique=True, verbose_name=b'uniq_hash')),
            ],
            options={
                'ordering': ('p_stage', 'notes'),
            },
        ),
        migrations.AddField(
            model_name='method',
            name='method_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methods.MethodSet'),
        ),
    ]
